id = "tscoder"
name = "TSCoder"
description = "The open source coding agent."
version = "1.1.53"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/tscoder"

[agent_servers.tscoder]
name = "TSCoder"
icon = "./icons/tscoder.svg"

[agent_servers.tscoder.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/tscoder/releases/download/v1.1.53/tscoder-darwin-arm64.zip"
cmd = "./tscoder"
args = ["acp"]

[agent_servers.tscoder.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/tscoder/releases/download/v1.1.53/tscoder-darwin-x64.zip"
cmd = "./tscoder"
args = ["acp"]

[agent_servers.tscoder.targets.linux-aarch64]
archive = "https://github.com/anomalyco/tscoder/releases/download/v1.1.53/tscoder-linux-arm64.tar.gz"
cmd = "./tscoder"
args = ["acp"]

[agent_servers.tscoder.targets.linux-x86_64]
archive = "https://github.com/anomalyco/tscoder/releases/download/v1.1.53/tscoder-linux-x64.tar.gz"
cmd = "./tscoder"
args = ["acp"]

[agent_servers.tscoder.targets.windows-x86_64]
archive = "https://github.com/anomalyco/tscoder/releases/download/v1.1.53/tscoder-windows-x64.zip"
cmd = "./tscoder.exe"
args = ["acp"]
