#!/usr/bin/env node

import path from "path"
import fs from "fs/promises"
import { fileURLToPath } from "url"
import { execSync } from "child_process"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

// Read package.json
const pkg = JSON.parse(await fs.readFile(path.join(dir, "package.json"), "utf-8"))

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"

// Fetch and generate models.dev snapshot
console.log("Fetching models data...")
let modelsData
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await fs.readFile(process.env.MODELS_DEV_API_JSON, "utf-8")
} else {
  const response = await fetch(`${modelsUrl}/api.json`)
  modelsData = await response.text()
}

await fs.writeFile(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build-npm.mjs - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Clean dist
console.log("Cleaning dist...")
try {
  await fs.rm(path.join(dir, "dist"), { recursive: true, force: true })
} catch {}

// Create dist directory
const distDir = path.join(dir, "dist")
await fs.mkdir(distDir, { recursive: true })

// Build with esbuild
console.log("Building with esbuild...")

try {
  const externals = [
    "@opentui/core",
    "@parcel/watcher",
    "tree-sitter",
    "tree-sitter-bash",
    "@standard-community/standard-json",
    "@standard-community/standard-openapi",
    "@gitlab/opencode-gitlab-auth",
    "@gitlab/gitlab-ai-provider",
    "web-tree-sitter",
    "bun-pty",
  ].map(e => `--external:${e}`).join(" ")
  execSync(`npx esbuild ./src/index.ts --bundle --platform=node --target=node20 --format=esm --outfile=${path.join(distDir, "index.js")} --sourcemap ${externals}`, {
    cwd: dir,
    stdio: "inherit",
  })
  console.log("Build completed successfully!")
} catch (error) {
  console.error("Build failed:", error.message)
  process.exit(1)
}

// Create package.json for dist
await fs.writeFile(
  path.join(distDir, "package.json"),
  JSON.stringify({
    name: pkg.name,
    version: pkg.version,
    type: "module",
    main: "./index.js",
    bin: {
      tscoder: "./index.js"
    }
  }, null, 2)
)

console.log(`Build complete: ${distDir}`)
console.log(`Output: ${path.join(distDir, "index.js")}`)
