#!/usr/bin/env node

import path from "path";
import fs from "fs/promises";
import { exec } from "child_process";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dir = path.resolve(__dirname, "..");

process.chdir(dir);

// Dynamically import solidPlugin to handle monorepo structure
async function resolveSolidPlugin() {
  try {
    const solidPluginPath = path.resolve(dir, "node_modules", "@opentui", "solid", "scripts", "solid-plugin.js");
    const { default: solidPlugin } = await import(solidPluginPath);
    return solidPlugin;
  } catch (error) {
    console.error("Error loading solidPlugin:", error);
    throw error;
  }
}

async function runCommand(cmd, options = {}) {
  return new Promise((resolve, reject) => {
    exec(cmd, options, (error, stdout, stderr) => {
      if (error) {
        console.error(`Error running command: ${cmd}`);
        console.error(stderr);
        reject(error);
        return;
      }
      resolve(stdout);
    });
  });
}

async function main() {
  try {
    const solidPlugin = await resolveSolidPlugin();
    const pkg = JSON.parse(await fs.readFile(path.join(dir, "package.json"), "utf8"));
    const Script = (await import("@tscoder/script")).Script;
    const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev";
    
    // Fetch and generate models.dev snapshot
    const modelsData = process.env.MODELS_DEV_API_JSON
      ? await fs.readFile(process.env.MODELS_DEV_API_JSON, "utf8")
      : await fetch(`${modelsUrl}/api.json`).then((x) => x.text());
    
    await fs.writeFile(
      path.join(dir, "src/provider/models-snapshot.ts"),
      `// Auto-generated by build.js - do not edit\nexport const snapshot = ${modelsData} as const\n`,
      "utf8"
    );
    console.log("Generated models-snapshot.ts");

    const singleFlag = process.argv.includes("--single");
    const baselineFlag = process.argv.includes("--baseline");
    const skipInstall = process.argv.includes("--skip-install");

    const allTargets = [
      { os: "linux", arch: "arm64" },
      { os: "linux", arch: "x64" },
      { os: "linux", arch: "x64", avx2: false },
      { os: "linux", arch: "arm64", abi: "musl" },
      { os: "linux", arch: "x64", abi: "musl" },
      { os: "linux", arch: "x64", abi: "musl", avx2: false },
      { os: "darwin", arch: "arm64" },
      { os: "darwin", arch: "x64" },
      { os: "darwin", arch: "x64", avx2: false },
      { os: "win32", arch: "x64" },
      { os: "win32", arch: "x64", avx2: false }
    ];

    const targets = singleFlag
      ? allTargets.filter((item) => {
          if (item.os !== process.platform || item.arch !== process.arch) {
            return false;
          }

          if (item.avx2 === false) {
            return baselineFlag;
          }

          if (item.abi !== undefined) {
            return false;
          }

          return true;
        })
      : allTargets;

    await runCommand("rm -rf dist");

    const binaries = {};
    if (!skipInstall) {
      await runCommand(`npm install --os=* --cpu=* @opentui/core@${pkg.dependencies["@opentui/core"]}`);
      await runCommand(`npm install --os=* --cpu=* @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`);
    }

    for (const item of targets) {
      const name = [
        pkg.name,
        item.os === "win32" ? "windows" : item.os,
        item.arch,
        item.avx2 === false ? "baseline" : undefined,
        item.abi === undefined ? undefined : item.abi
      ]
        .filter(Boolean)
        .join("-");
      
      console.log(`building ${name}`);
      await runCommand(`mkdir -p dist/${name}/bin`);

      const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"));
      const workerPath = "./src/cli/cmd/tui/worker.ts";

      // Use platform-specific bunfs root path based on target OS
      const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/";
      const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/");

      // For non-Bun build, we'll use esbuild directly
      await runCommand(`npx esbuild ./src/index.ts ${parserWorker} ${workerPath} \
        --bundle \
        --platform=node \
        --outdir=dist/${name}/bin \
        --sourcemap=external \
        --define:OPENCODE_VERSION='"${Script.version}"' \
        --define:OTUI_TREE_SITTER_WORKER_PATH='"${bunfsRoot}${workerRelativePath}"' \
        --define:OPENCODE_WORKER_PATH='"${workerPath}"' \
        --define:OPENCODE_CHANNEL='"${Script.channel}"' \
        --define:OPENCODE_LIBC='"${item.os === "linux" ? (item.abi ?? "glibc") : ""}"'`);

      await runCommand(`rm -rf ./dist/${name}/bin/tui`);
      
      await fs.writeFile(
        path.join(dir, `dist/${name}/package.json`),
        JSON.stringify(
          {
            name,
            version: Script.version,
            os: [item.os],
            cpu: [item.arch]
          },
          null,
          2
        ),
        "utf8"
      );
      
      binaries[name] = Script.version;
    }

    if (Script.release) {
      for (const key of Object.keys(binaries)) {
        if (key.includes("linux")) {
          await runCommand(`tar -czf ../../${key}.tar.gz *`, { cwd: `dist/${key}/bin` });
        } else {
          await runCommand(`zip -r ../../${key}.zip *`, { cwd: `dist/${key}/bin` });
        }
      }
      await runCommand(`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`);
    }

    console.log("Build completed successfully!");
    return { binaries };
  } catch (error) {
    console.error("Build failed:", error);
    process.exit(1);
  }
}

main();
